/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface RemyTypography {
        "variant": 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p' | 'link';
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLRemyTypographyElement extends Components.RemyTypography, HTMLStencilElement {
    }
    var HTMLRemyTypographyElement: {
        prototype: HTMLRemyTypographyElement;
        new (): HTMLRemyTypographyElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "remy-typography": HTMLRemyTypographyElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface RemyTypography {
        "variant"?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p' | 'link';
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "remy-typography": RemyTypography;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "remy-typography": LocalJSX.RemyTypography & JSXBase.HTMLAttributes<HTMLRemyTypographyElement>;
        }
    }
}
